- name: Install Samba package
  tags: samba
  package:
    name:
      - "{{ fileserver_package_name }}"
    state: latest

- name: Start and enable Samba service
  tags: samba
  service:
   name: "{{ fileserver_service }}"
   state: started
   enabled: yes