---

- hosts: all
  become: true
  tasks:

  - name: Install Apache2 and PHP packages on Ubuntu/Debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]
  
  - name: Install Httpd and PHP packages on CentOS
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install Httpd and PHP packages on Fedora
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"