---

- hosts: all
  become: true
  tasks:

  - name: Remove Apache and PHP for Ubuntu/Debian
    package:
      name: 
        - libapache2-mod-php
        - apache2
      state: absent
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Remove Httpd and PHP for CentOS
    yum:
      name: 
        - php
        - httpd
      state: absent
    when: ansible_distribution == "CentOS"

  - name: Remove Httpd and PHP on Fedora
    dnf:
      name: 
        - php
        - httpd
      state: absent
    when: ansible_distribution == "Fedora"