---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install updates (Ubuntu/Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Install updates (Fedora)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

- hosts: web_servers
  become: true
  tasks:
    
  - name: Install Apache2 and PHP packages on Ubuntu/Debian
    tags: apache, apache2, ubuntu, debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
  
  - name: Install Httpd and PHP packages on CentOS
    tags: apache, httpd, centos
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install Httpd and PHP packages on Fedora
    tags: apache, httpd, fedora
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

- hosts: db_servers
  become: true
  tasks:
   
  - name: Install MariaDB package (CentOS)
    tags: mariadb, centos
    yum:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install MariaDB package (Fedora)
    tags: mariadb, fedora
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Install MariaDB package (Ubuntu/Debian)
    tags: mariadb, ubuntu, debian
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: file_servers
  become: true
  tasks:
   
  - name: Install Samba package
    tags: samba
    package:
      name:
        - samba
      state: latest