---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install updates (Ubuntu/Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Install updates (Fedora)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

- hosts: workstations
  become: true
  tasks:
    
    - name: Install unzip
      package:
        name: unzip

    - name: Install Terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root

- hosts: web_servers
  become: true
  tasks:
    
  - name: Install Apache2 and PHP packages on Ubuntu/Debian
    tags: apache, apache2, ubuntu, debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
  
  - name: Install Httpd and PHP packages on CentOS
    tags: apache, httpd, centos
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install Httpd and PHP packages on Fedora
    tags: apache, httpd, fedora
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
   
  - name: Install MariaDB package (CentOS)
    tags: mariadb, centos
    yum:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install MariaDB package (Fedora)
    tags: mariadb, fedora
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Install MariaDB package (Ubuntu/Debian)
    tags: mariadb, ubuntu, debian
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: file_servers
  become: true
  tasks:
   
  - name: Install Samba package
    tags: samba
    package:
      name:
        - samba
      state: latest