- name: Install Apache and PHP packages
  tags: apache, httpd, php
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: Start and enable Apache service
  tags: apache, httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Change e-mail address for Default site (Ubuntu/Debian)
  tags: apache, apache2, ubuntu
  replace:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '^(\t+)ServerAdmin(\s+.*)?$'
    replace: '\tServerAdmin someone@someone.net'
  when: ansible_distribution in ["Debian", "Ubuntu"]
  notify: restart_apache

- name: Change e-mail address for admin in Httpd (CentOS/Fedora)
  tags: apache, centos, httpd, fedora
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin test@test.com
  when: ansible_distribution in ["CentOS","Fedora"]
  notify: restart_apache

- name: Copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644