- name: Add ssh key for Simone
  tags: always
  authorized_key:
    user: Simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIoTd0VqS5LZPbqrdBdieKj4m25cj+tPHjwSb67yD/WN Dedicated Ansible"

- name: OpenSSH | Generate sshd_config file from template
  tags: ssh
  template:
   src: "{{ ssh_template_file }}"
   dest: /etc/ssh/sshd_config
   owner: root
   group: root
   mode: 0644
  notify: restart_sshd