- name: Install MariaDB package (CentOS)
  tags: mariadb, centos
  yum:
    name:
      - mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install MariaDB package (Fedora)
  tags: mariadb, fedora
  dnf:
    name:
      - mariadb
    state: latest
  when: ansible_distribution == "Fedora"

- name: Install MariaDB package (Ubuntu/Debian)
  tags: mariadb, ubuntu, debian
  apt:
    name:
      - mariadb-server
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]