- name: Install MariaDB package
  tags: mariadb
  package:
    name:
      - "{{ database_package_name }}"
    state: latest

- name: Start and enable MariaDB service
  tags: mariadb
  service:
    name: "{{ database_service }}"
    state: started
    enabled: yes