- name: Install unzip
  package:
    name: unzip

- name: Install Terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root